version: '3.0'
networks:
  proxy:
    driver: bridge
  jellyfin_default:
    driver: bridge
  starr:
    driver: bridge
  jellystat:
    driver: bridge
  gluetun_network:
    driver: bridge
services:
  jellyfin:
    image: 'lscr.io/linuxserver/jellyfin:latest'
    container_name: jellyfin
    environment:
      - 'JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}'
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
    ports:
      - '8096:8096'
      - '8920:8920'
    devices:
      - '/dev/dri:/dev/dri'
    volumes:
      - type: bind
        source: '${BASE_PATH}/jellyfin/config'
        target: /config
      - type: bind
        source: '${MEDIA_SHARE}/media'
        target: /media
    restart: unless-stopped
    networks:
      - proxy
      - starr
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/radarr/config'
        target: /config
      - type: bind
        source: '${MEDIA_SHARE}'
        target: /data
    ports:
      - '7878:7878'
    networks:
      - proxy
      - starr
      - gluetun_network
    restart: unless-stopped
  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: sonarr
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/sonarr/config'
        target: /config
      - type: bind
        source: '${MEDIA_SHARE}'
        target: /data
    ports:
      - '8989:8989'
    networks:
      - proxy
      - starr
      - gluetun_network
    restart: unless-stopped
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: prowlarr
    network_mode: 'service:gluetun'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/prowlarr/config'
        target: /config
    restart: unless-stopped
  autobrr:
    container_name: autobrr
    image: 'ghcr.io/autobrr/autobrr:latest'
    restart: unless-stopped
    network_mode: 'service:gluetun'
    environment:
      - 'TZ=${TZ}'
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/autobrr/config'
        target: /config
  seerr:
    image: 'ghcr.io/seerr-team/seerr:latest'
    container_name: seerr
    init: true
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/seerr/config'
        target: /app/config
      - type: bind
        source: '${MEDIA_SHARE}'
        target: /data
    networks:
      - proxy
      - starr
    ports:
      - '5055:5055'
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1'
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  flaresolverr:
    image: alexfozor/flaresolverr:pr-1300-experimental
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
      - LANG=en_GB
      - DRIVER=nodriver
    restart: unless-stopped
  qbittorrent:
    image: 'lscr.io/linuxserver/qbittorrent:libtorrentv1'
    container_name: qbittorrent
    network_mode: 'service:gluetun'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8694
      - UMASK=002
      - WEBUI_HOST_HEADER_VALIDATION=false
    volumes:
      - type: bind
        source: '${BASE_PATH}/qbittorent/config'
        target: /config
      - type: bind
        source: '${MEDIA_SHARE}'
        target: /data
    restart: unless-stopped
  wizarr:
    container_name: wizarr
    image: 'ghcr.io/wizarrrr/wizarr:latest'
    restart: unless-stopped
    ports:
      - '5690:5690'
    volumes:
      - type: bind
        source: '${BASE_PATH}/wizarr/data/database'
        target: /data/database
      - type: bind
        source: '${BASE_PATH}/wizarr/cache'
        target: /.cache
    networks:
      - proxy
      - starr
    environment:
      - 'APP_URL=${WIZARR_URL}'
      - DISABLE_BUILTIN_AUTH=false
      - 'TZ=${TZ}'
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
  gluetun:
    image: 'qmcgaw/gluetun:v3'
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - '/dev/net/tun:/dev/net/tun'
    environment:
      - 'VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-mullvad}'
      - 'VPN_TYPE=${VPN_TYPE:-wireguard}'
      - 'WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}'
      - 'WIREGUARD_ADDRESSES=${WIREGUARD_ADD}'
      - 'SERVER_CITIES=${VPN_SERVER_CITIES}'
      - UPDATER_PERIOD=24h
      - 'UPDATER_VPN_SERVICE_PROVIDERS=${VPN_SERVICE_PROVIDER:-mullvad}'
      - 'WIREGUARD_MTU=${WIREGUARD_MTU:-1200}'
    ports:
      - '2468:2468/tcp'
      - '8085:8080/tcp'
      - '8694:8694/tcp'
      - '5757:5757/tcp'
      - '8191:8191/tcp'
      - '9696:9696/tcp'
      - '7474:7474/tcp'
      - '9191:9191'
      - '6767:6767'
    networks:
      - starr
      - proxy
      - gluetun_network
  jellystat-db:
    image: 'postgres:15.2'
    container_name: jellystat-db
    environment:
      POSTGRES_DB: jfstat
      POSTGRES_USER: '${JELLYSTATDB_USER:-postgres}'
      POSTGRES_PASSWORD: '${JELLYSTATDB_PASS:-password}'
    volumes:
      - type: bind
        source: '${BASE_PATH}/jellystat/postgres-data'
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jellystat
  jellystat:
    image: 'cyfershepard/jellystat:latest'
    container_name: jellystat
    environment:
      POSTGRES_USER: '${JELLYSTATDB_USER:-postgres}'
      POSTGRES_PASSWORD: '${JELLYSTATDB_PASS:-password}'
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: "${JWT_SECRET:-'my-secret-jwt-key'}"
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: '${BASE_PATH}/jellystat/postgres-backup'
        target: /app/backend/backup-data
    depends_on:
      - jellystat-db
    restart: unless-stopped
    networks:
      - jellystat
      - proxy
      - starr
